language: node_js

node_js:
  - 10

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows

env:
  global:
    - npm_config_jobs=max

git:
  depth: 10

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  skip_cleanup: true
  on:
    tags: true
  provider: script
  script: npm install -g prebuild@9.1.1 && npm run pre-build && npm run pre-build:upload -u ${PREBUILD_UPLOAD}
